[package]
name = "blender-armature"
version = "0.0.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
description = "Serialize / deserialize Blender armatures"
keywords = ["blender", "skeleton", "armature", "bone", "vertex"]
license = "MIT"
repository = "https://github.com/chinedufn/landon"
documentation = "https://docs.rs/landon"

[dependencies]
failure = "0.1.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
cgmath = "0.16"
