# TODO: Move the book building process to azure pipelines and delete .travis.yml
language: rust

os: linux

cache:
    - cargo

matrix:
  include:
    # Build documentation for the gh-pages branch
    - rust: nightly
      env: JOB=book-build-and-deploy
      cache:
        directories:
          - $HOME/.cargo
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
        - cargo install-update -a
      script:
        - (cd guide && mdbook build)
        - cargo doc --no-deps -p blender-mesh -p blender-armature
        - mv target/doc guide/book/api
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        local-dir: guide/book
        keep-history: false
      if: branch = master

notifications:
  email:
    on_success: never
