[package]
name = "blender-exporter"
version = "0.0.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
publish = true
description = "Tooling for exporting data such as meshes and armatures from Blender"
keywords = ["blender", "export", "exporter", "mesh", "armature"]
license = "MIT"
repository = "https://github.com/chinedufn/blender-exporter"
documentation = "https://docs.rs/blender-exporter"

[dependencies]
blender-armature = { version = "0.1.0", path = "./blender-armature" }
blender-mesh = { version = "0.0.2", path = "./blender-mesh" }

[dev-dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"

[workspace]
members = [
  "blender-armature",
  "blender-mesh",
  "mesh-visualizer"
]
