[package]
name = "landon"
version = "0.0.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
publish = true
description = "A collection of heavily unit and integration tested tooling, data structures and methods for exporting data (such as meshes and armatures) from 3d modeling software and preparing it for your rendering pipeline."
keywords = ["blender", "export", "exporter", "mesh", "armature"]
license = "MIT"
repository = "https://github.com/chinedufn/landon"
documentation = "https://docs.rs/landon"

[dependencies]
blender-armature = { version = "0.0.1", path = "./blender-armature" }
blender-mesh = { version = "0.1.0", path = "./blender-mesh" }

[dev-dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"

[workspace]
members = [
  # TODO: Rename to `Mesh` and `Armature`
  "blender-armature",
  "blender-mesh",
  "mesh-visualizer"
]
