[package]
name = "mesh-visualizer"
version = "0.0.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.4"
blender-mesh = { path = "../blender-mesh" }
blender-armature = { path = "../blender-armature" }
cgmath = "0.16"

[build-dependencies]
blender-mesh = { path = "../blender-mesh" }
blender-armature = { path = "../blender-armature" }
serde = "1.0"
serde_json = "1.0"

[profile.release]
# Include function names in the `.wasm` for better debugging and
# profiling. Comment this out if you're trying to create the smallest `.wasm`
# binaries you can.
# debug = true

# # Uncomment these lines to create smaller `.wasm` binaries, at the cost of
# # longer compile times.
codegen-units = 1
incremental = false
lto = true
opt-level = "z"
